module
public import Mathlib
@[expose] public section

open CategoryTheory

universe v u
variable {R : Type u} [CommRing R] [DecidableEq R] (C : Type u) [Category C]
variable {n : ℕ}

structure KLRWCategory (n : ℕ) (R : Type u) where
  positioning : Fin (n + 1)

/--
The free module generated by the strands with fixed channels.
This is an abbrev because we want it to inherit the Module typeclass instance from DFinsupp.

Uses DFinsupp because Finsupp is not currently computable. See
https://leanprover.zulipchat.com/#narrow/channel/113489-new-members/topic/Finsupp.20noncomputability
-/
abbrev StrandSpace (R : Type u) [CommRing R] : Type u := Π₀ _ : ℕ, R

abbrev StrandSpace.dots (R : Type u) [CommRing R] (n : ℕ) : StrandSpace R :=
  DFinsupp.single n 1

instance : Category (KLRWCategory n R) where
  Hom X Y := StrandSpace R
  id X := StrandSpace.dots R 0
  comp {X Y Z} g h :=
    g.sum (fun i r => h.sum (fun j s => (r * s) • StrandSpace.dots R (i + j + 0)))
  id_comp := by
    intro X Y f
    sorry
  comp_id := by
    intro X Y f
    sorry
  assoc := by
    intro X Y Z f g h
    sorry

instance : Preadditive (KLRWCategory n R) where
  --bilinearity
  homGroup P Q := inferInstanceAs (AddCommGroup (StrandSpace R))
  add_comp := by
    intro P Q S f f' g
    sorry
  comp_add := by
    intro P Q S f g g'
    sorry

abbrev AddKLRWCategory (n : ℕ) (R : Type u) [CommRing R] [DecidableEq R] : Type _ :=
  Mat_ (KLRWCategory n R)

abbrev KLRWComplexCategory (n : ℕ) (R : Type u) [CommRing R] [DecidableEq R] : Type _ :=
  CochainComplex (AddKLRWCategory n R) ℤ
